"""Init

Revision ID: 024a3465b4b4
Revises: 5fb1ecd5e7c3
Create Date: 2023-04-03 01:13:07.614950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '024a3465b4b4'
down_revision = '5fb1ecd5e7c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
