"""Init

Revision ID: 5fb1ecd5e7c3
Revises: 0a2aeaeed0ec
Create Date: 2023-04-03 01:11:14.294761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb1ecd5e7c3'
down_revision = '0a2aeaeed0ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
